import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>

        <footer
          style={{
            textAlign: "center",
            marginTop: "3rem",
            fontSize: "0.9rem",
            color: "#555",
          }}
        >
          Made with ❤️ by{" "}
          <a href="https://hamedakbri.ir" className="font-bold">
            Hamed Akbari
          </a>
        </footer>
      </body>
    </html>
  );
}
